### ISSUE TITLE
Reconcile: 1.2 roadmap

### ISSUE THREAD

**Issue by Zarthus** [Zarthus/Reconcile#59]
All Reconcile issues will now no longer be assigned to the 1.2 milestone (unless it is a security issue), and we will work towards pushing a stable 1.2 release.

The following changes should be done before the release is done:

- [x] Bindhost support
- [x] Cloud2Butt.py to disabled modules by default
- [x] Cloud2Butt.py ignores irccloud.com
- [x] Include LICENSE text in every file that is native to Reconcile.
- [ ] Flooddetect improvements for Reconcile (#58)  (moved to 1.3)
- [x] Add ban() option (#57)
- [x] Introduce callbacks (#56)
- [x] Title.py optimization (#55) 
- [x] tell.py modifications (#53)
- [x] Urltools.py improvements (#52) 
- [x] Verify google.py still works (#50)
- [x] Ensure Reconcile does not get stuck in query loops (#49) 
- [x] Config option auth_string (#46) 
- [x] Google doesn't html escape (#45)
- [x] Figure a way to update config.json with latest version (#42)
- [x] Reconnecting does not properly close the socket (#40) 
- [x] Module: urlshorten.py
- [x] Add `action` command in basics.py 
- [x] `travis` was renamed to `.travis`  
- [x] Fixed missing colon in `mode()`  
- [x] tools/formatter.py fix for $(random)
- [x] cloud2butt improvements, can ignore nicks now.
- [x] Better rate limitation options for modules
- [x] Implement CTCP response `CLIENTINFO`
- [x] Several fixes to test_module.py
